import type { Config } from "tailwindcss";

// Design tokens lifted verbatim from the Stitch "Editorial Infrastructure"
// design system export (savannah_nexus/DESIGN.md) so visual output matches
// the approved Stitch screens exactly.
const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#799dd6",
        "tertiary-fixed-dim": "#ffb59c",
        "tertiary-container": "#611b00",
        "secondary-container": "#90efef",
        tertiary: "#3d0e00",
        "on-secondary-fixed": "#002020",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "primary-fixed": "#d5e3ff",
        "on-secondary-container": "#006e6e",
        "surface-dim": "#d8dadc",
        "surface-tint": "#3a5f94",
        "inverse-primary": "#a7c8ff",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed-variant": "#1f477b",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-container": "#ff6f3a",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed": "#ffdbcf",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#832700",
        "on-secondary-fixed-variant": "#004f4f",
        "on-primary-fixed": "#001b3c",
        secondary: "#006a6a",
        "inverse-on-surface": "#eff1f3",
        "surface-container-highest": "#e0e3e5",
        error: "#ba1a1a",
        primary: "#001e40",
        background: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#76d6d5",
        "outline-variant": "#c3c6d1",
        "primary-container": "#003366",
        "on-primary": "#ffffff",
        "surface-container": "#eceef0",
        "on-surface-variant": "#43474f",
        "primary-fixed-dim": "#a7c8ff",
        "on-secondary": "#ffffff",
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        outline: "#737780",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#93f2f2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        newsreader: ["var(--font-newsreader)", "serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
        headline: ["var(--font-newsreader)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "1.1" }],
        "headline-md": ["1.75rem", { lineHeight: "1.25" }],
        "title-lg": ["1.375rem", { lineHeight: "1.4" }],
        "body-md": ["0.875rem", { lineHeight: "1.5" }],
        "label-md": ["0.75rem", { lineHeight: "1.3" }],
      },
      boxShadow: {
        whisper: "0 8px 32px rgba(25, 28, 30, 0.06)",
        "whisper-lg": "0 8px 40px -12px rgba(25, 28, 30, 0.06)",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #001e40 0%, #003366 100%)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
